### ISSUE TITLE
1.0 Checklist

### ISSUE THREAD

**Issue by nkolba** [FDC3/FDC3#32]
## Website changes
- [x] Iconography (own images and/or attribution)
- [x] Use case updates
- [x] Transfer latest from use case repo
	- [x] Remove people lists from use case overview
        - [x] Remove all but accepted use cases (talk to JT, Saori, Kat, Johan, Riko this week!)
- [x] Add links to working group wikis into  Community section
- [x] Move why FDC3 to about section
- [x] Updates to Why FDC3, Intents Overview, and Context Overview (Nick)
- [x] Add get involved CTA (fdc3@finos.org) to Community, footer
- [x] Add Docusaurus versioning
- [x] Add "Used by" section to front page

## Repo changes
- [x] tag version 1.0-beta + release notes

## Other changes
- [x] Make sure news works with versioning
- [x] Retire old partial FDC3 websites
- [x] Update working group repos to point to combined repo
- [x] Transfer open issues/PRs from working group repos
- [x] Archive working group repos
- [x] Point fdc3.org to fdc3.finos.org (or remove)

## Release Preparation
- [x] Repo and website promote to version 1.0
- [ ] Write a 1.0 blog post pointing to press release
- [x] Change FINOS badge in README from "Incubating" to "Released" (see https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530371/Released)
- [x] Tag code as v1.0 and add release notes

**Comment by brooklynrob** [comment]
As part of the overall go-live check-list for FDC3 1.0, it would be helpful for everyone to review and refresh themselves on the [Activation stage (stage before release)](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530376/Activation).

**Comment by brooklynrob** [comment]
Here is the board approved [active participation policy](https://www.finos.org/hubfs/FINOS/governance/FINOS%20Active%20Participation%20Policy%202018-12-12.pdf?hsLang=en-us) -- context and a consideration for what logos appear.

**Comment by brooklynrob** [comment]
Here is the alpha version of the [active participation report for FDC3](https://metrics.finos.org/app/kibana#/dashboard/77b05c60-3e60-11e9-9e7c-eb1eab055f1f?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(description:'Tracking%20active%20participation%20for%20projects%20and%20working%20groups',filters:!(('$state':(store:appState),meta:(alias:!n,controlledBy:'1549670541857',disabled:!f,index:affiliations,key:cm_program,negate:!f,params:(query:FDC3,type:phrase),type:phrase,value:FDC3),query:(match:(cm_program:(query:FDC3,type:phrase))))),fullScreenMode:!f,options:(darkTheme:!f,hidePanelTitles:!f,useMargins:!t),panels:!((gridData:(h:3,i:'5',w:4,x:4,y:0),id:'85eb03d0-2bfe-11e9-9e7c-eb1eab055f1f',panelIndex:'5',type:visualization,version:'6.1.4-1'),(gridData:(h:5,i:'6',w:6,x:6,y:3),id:'0a0c9650-2c00-11e9-9e7c-eb1eab055f1f',panelIndex:'6',title:'Working%20Groups',type:visualization,version:'6.1.4-1'),(gridData:(h:5,i:'7',w:6,x:0,y:3),id:a8a63330-2bff-11e9-9e7c-eb1eab055f1f,panelIndex:'7',title:Projects,type:visualization,version:'6.1.4-1'),(gridData:(h:3,i:'8',w:4,x:0,y:0),id:'445e2200-2c01-11e9-9e7c-eb1eab055f1f',panelIndex:'8',type:visualization,version:'6.1.4-1'),(gridData:(h:3,i:'9',w:3,x:8,y:0),id:fab80fd0-2e0d-11e9-9e7c-eb1eab055f1f,panelIndex:'9',type:visualization,version:'6.1.4-1'),(gridData:(h:5,i:'10',w:6,x:0,y:8),id:'43693e90-3e74-11e9-9e7c-eb1eab055f1f',panelIndex:'10',type:visualization,version:'6.1.4-1'),(gridData:(h:5,i:'11',w:6,x:6,y:8),id:'6b3df050-3e83-11e9-9e7c-eb1eab055f1f',panelIndex:'11',type:visualization,version:'6.1.4-1'),(gridData:(h:4,i:'12',w:6,x:0,y:13),id:b06ed710-3e84-11e9-9e7c-eb1eab055f1f,panelIndex:'12',type:visualization,version:'6.1.4-1'),(gridData:(h:4,i:'13',w:6,x:6,y:13),id:c4b978e0-3e86-11e9-9e7c-eb1eab055f1f,panelIndex:'13',type:visualization,version:'6.1.4-1')),query:(language:lucene,query:''),timeRestore:!f,title:'Active%20Participation%20Dashboard%20(Bitergia%20Work%20in%20Progress)',uiState:(P-1:(vis:(params:(config:(searchKeyword:''),sort:(columnIndex:4,direction:desc)))),P-10:(vis:(params:(config:(searchKeyword:''),sort:(columnIndex:5,direction:desc)))),P-11:(vis:(params:(config:(searchKeyword:''),sort:(columnIndex:6,direction:desc)))),P-12:(vis:(params:(config:(searchKeyword:''),sort:(columnIndex:5,direction:desc)))),P-13:(vis:(params:(config:(searchKeyword:''),sort:(columnIndex:6,direction:desc)))),P-2:(vis:(params:(config:(searchKeyword:''),sort:(columnIndex:4,direction:desc)))),P-3:(vis:(params:(config:(searchKeyword:''),sort:(columnIndex:6,direction:desc)))),P-4:(vis:(params:(config:(searchKeyword:''),sort:(columnIndex:6,direction:desc))))),viewMode:view)) -- related to topic of active participation.

**Comment by brooklynrob** [comment]
At our 3/14 meeting decision on including logos on fdc3.finos.org was

- Any active participant orgs per the active participation policy who are also FINOS members are automatically included.
- Any active participant orgs per the active participation policy who are NOT FINOS members may opt-in to have their logos included.
- Logo order will be function of FINOS member metals (Platinum -> Gold -> Silver -> At Large), and then non-member participating orgs; within these respective groups logos will be alphabetical.

**Comment by nkolba** [comment]
1.0 released.  closing this out.
