### ISSUE TITLE
1.0 documentation completion task list

### ISSUE THREAD

**Issue by rikoe** [FDC3/FDC3#6]
Tasks:
- [ ] About page (Information about the FDC3 and its mission)
- [ ] Community page (Information and links to FINOS)
- [ ] News/blogs area (remove existing sample content, add real content, e.g. the news link on https://fdc3.org)
- [ ] Apply website versioning (first version should be either 0.9 or 1.0-beta)
  - See https://docusaurus.io/docs/en/versioning.
  - Should link back to a version tag in GitHub with release notes.
  - See how Docusaurus have done it: https://docusaurus.io/en/versions.
- [ ] Repository versioning guidelines (i.e. tags and release notes)
- [ ] Documentation improvements & extra content (TBD)
- [ ] An extra page under the docs for each area with the working group info from the wiki
- [ ] Users/members section with logos from https://www.finos.org/fdc3
- [ ] FINOS banner on landing page (from current fdc3.finos.org): "Proud member of the Fintech Opensource Foundation", with logo
- [ ] Use case description on landing page

Assets:
- [ ] FDC3 Favicon
- [ ] FDC3 logo on main page (above "Open standards for the financial desktop")
- [ ] Icons for four main areas on landing page, or include attribution for existing icons are from NounProject (e.g see how https://redux.js.org/ does icon attribution)
- [ ] Small FDC3 icon in blue banner across the top (currently FINOS logo)
- [ ] Large FDC3 icon in footer (currently FINOS logo)
- [ ] Schema images:
  - https://rikoe.github.io/FDC3/docs/api/api-spec - 3 schemas 
  - https://rikoe.github.io/FDC3/docs/appd-discovery - 3 schemas 
  - https://rikoe.github.io/FDC3/docs/appd-use - 3 schemas 
  - https://rikoe.github.io/FDC3/docs/use-cases/use-cases-intro - 1 schema

**Comment by nkolba** [comment]
Replaced by issue #32
